launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3

local-address=0.0.0.0
local-port=53

api=yes
api-key=replace-me
webserver=yes
webserver-address=127.0.0.1
webserver-port=8081
webserver-allow-from=127.0.0.1

default-soa-content=ns1.pirate dns.pirate 0 3600 900 1209600 300
default-ttl=300

version-string=anonymous
setuid=
setgid=
