import { existsSync } from "node:fs";
import { parse } from "yaml";
import { IMPLEMENTED_BUNDLE_FILE } from "./_shared";
import { loadSourceSchemas, type BundleSpec, TypeGenerator } from "./_typegen";

const SOURCE_SCHEMA_DIR = "specs/api/src/components/schemas";
function defaultApiContractsDir(): string {
  if (existsSync("../api/services/contracts")) {
    return "../api/services/contracts";
  }
  if (existsSync("../../api/services/contracts")) {
    return "../../api/services/contracts";
  }
  if (existsSync("../../../api/services/contracts")) {
    return "../../../api/services/contracts";
  }
  return "../api/services/contracts";
}

const API_CONTRACTS_DIR = process.env.API_CONTRACTS_DIR || defaultApiContractsDir();
const OUTPUT_FILE = process.env.API_CONTRACTS_OUTPUT_FILE || `${API_CONTRACTS_DIR}/src/index.ts`;

const TYPE_EXPORTS = [
  { name: "ErrorResponse", ref: "#/components/schemas/Error" },
  {
    name: "AuthProof",
    ref: "#/paths/~1auth~1session~1exchange/post/requestBody/content/application~1json/schema/properties/proof",
  },
  {
    name: "SessionExchangeRequest",
    ref: "#/paths/~1auth~1session~1exchange/post/requestBody/content/application~1json/schema",
  },
  { name: "OAuthDeviceAuthorizeRequest", ref: "#/components/schemas/OAuthDeviceAuthorizeRequest" },
  { name: "OAuthDeviceAuthorizeResponse", ref: "#/components/schemas/OAuthDeviceAuthorizeResponse" },
  { name: "OAuthDeviceVerifyRequest", ref: "#/components/schemas/OAuthDeviceVerifyRequest" },
  { name: "OAuthDeviceVerifyResponse", ref: "#/components/schemas/OAuthDeviceVerifyResponse" },
  { name: "OAuthDeviceTokenRequest", ref: "#/components/schemas/OAuthDeviceTokenRequest" },
  { name: "OAuthDeviceTokenResponse", ref: "#/components/schemas/OAuthDeviceTokenResponse" },
  { name: "OAuthDeviceAuthorizationPendingResponse", ref: "#/components/schemas/OAuthDeviceAuthorizationPendingResponse" },
  { name: "VerificationCapabilities", ref: "#/components/schemas/VerificationCapabilities" },
  { name: "User", ref: "#/components/schemas/User" },
  { name: "GlobalHandle", ref: "#/components/schemas/GlobalHandle" },
  { name: "Profile", ref: "#/components/schemas/Profile" },
  { name: "PublicProfileResolution", ref: "#/components/schemas/PublicProfileResolution" },
  { name: "CourtyardWalletInventoryResponse", ref: "#/components/schemas/CourtyardWalletInventoryResponse" },
  { name: "CourtyardWalletInventoryGroup", ref: "#/components/schemas/CourtyardWalletInventoryGroup" },
  { name: "AssetBalanceCapability", ref: "#/components/schemas/AssetBalanceCapability" },
  { name: "AssetBalanceCapabilityListResponse", ref: "#/components/schemas/AssetBalanceCapabilityListResponse" },
  { name: "NftGateCapabilitySource", ref: "#/components/schemas/NftGateCapabilitySource" },
  { name: "NftGateCapabilitySourceListResponse", ref: "#/components/schemas/NftGateCapabilitySourceListResponse" },
  { name: "NftGateFacetValue", ref: "#/components/schemas/NftGateFacetValue" },
  { name: "NftGateFacetValuePage", ref: "#/components/schemas/NftGateFacetValuePage" },
  { name: "NftGateCatalogUnavailableResponse", ref: "#/components/schemas/NftGateCatalogUnavailableResponse" },
  { name: "ProfileActivityPostPage", ref: "#/components/schemas/ProfileActivityPostPage" },
  { name: "ProfileActivityCommentPage", ref: "#/components/schemas/ProfileActivityCommentPage" },
  { name: "ProfileActivityResponse", ref: "#/components/schemas/ProfileActivityResponse" },
  { name: "WalletIdentityPublicName", ref: "#/components/schemas/WalletIdentityPublicName" },
  { name: "WalletIdentity", ref: "#/components/schemas/WalletIdentity" },
  { name: "WalletIdentityRedirect", ref: "#/components/schemas/WalletIdentityRedirect" },
  { name: "WalletIdentityResponse", ref: "#/components/schemas/WalletIdentityResponse" },
  { name: "PublicNameQuoteRequest", ref: "#/components/schemas/PublicNameQuoteRequest" },
  { name: "PublicNamePaymentInstructions", ref: "#/components/schemas/PublicNamePaymentInstructions" },
  { name: "PublicNameQuote", ref: "#/components/schemas/PublicNameQuote" },
  { name: "PublicNameClaimRequest", ref: "#/components/schemas/PublicNameClaimRequest" },
  { name: "PublicNameRegistration", ref: "#/components/schemas/PublicNameRegistration" },
  { name: "PublicNameRegistrationResponse", ref: "#/components/schemas/PublicNameRegistrationResponse" },
  { name: "PublicNameStatus", ref: "#/components/schemas/PublicNameStatus" },
  { name: "CommunityRoleSummary", ref: "#/components/schemas/CommunityRoleSummary" },
  { name: "RedditVerification", ref: "#/components/schemas/RedditVerification" },
  { name: "RedditImportSummary", ref: "#/components/schemas/RedditImportSummary" },
  { name: "OnboardingStatus", ref: "#/components/schemas/OnboardingStatus" },
  { name: "WalletAttachmentSummary", ref: "#/components/schemas/WalletAttachmentSummary" },
  { name: "VerificationSession", ref: "#/components/schemas/VerificationSession" },
  { name: "VerificationSessionLaunch", ref: "#/components/schemas/VerificationSessionLaunch" },
  { name: "VeryWidgetLaunch", ref: "#/components/schemas/VeryWidgetLaunch" },
  { name: "VerySessionBinding", ref: "#/components/schemas/VerySessionBinding" },
  { name: "RequestedVerificationCapability", ref: "#/components/schemas/RequestedVerificationCapability" },
  { name: "VerificationRequirement", ref: "#/components/schemas/VerificationRequirement" },
  { name: "VerificationIntent", ref: "#/components/schemas/VerificationIntent" },
  { name: "AgentOwnershipProvider", ref: "#/components/schemas/AgentOwnershipProvider" },
  { name: "AgentOwnershipSessionKind", ref: "#/components/schemas/AgentOwnershipSessionKind" },
  { name: "AgentOwnershipSessionStatus", ref: "#/components/schemas/AgentOwnershipSessionStatus" },
  { name: "UserAgentStatus", ref: "#/components/schemas/UserAgentStatus" },
  { name: "AgentHandleStatus", ref: "#/components/schemas/AgentHandleStatus" },
  { name: "AgentOwnershipState", ref: "#/components/schemas/AgentOwnershipState" },
  { name: "AgentChallenge", ref: "#/components/schemas/AgentChallenge" },
  { name: "AgentActionProof", ref: "#/components/schemas/AgentActionProof" },
  { name: "SelfAgentOwnershipLaunch", ref: "#/components/schemas/SelfAgentOwnershipLaunch" },
  { name: "ClawkeyRegistrationLaunch", ref: "#/components/schemas/ClawkeyRegistrationLaunch" },
  { name: "AgentOwnershipSessionLaunch", ref: "#/components/schemas/AgentOwnershipSessionLaunch" },
  { name: "StartAgentOwnershipSessionRequest", ref: "#/components/schemas/StartAgentOwnershipSessionRequest" },
  { name: "CompleteAgentOwnershipSessionRequest", ref: "#/components/schemas/CompleteAgentOwnershipSessionRequest" },
  { name: "AgentOwnershipPairing", ref: "#/components/schemas/AgentOwnershipPairing" },
  { name: "AgentOwnershipPairingClaimRequest", ref: "#/components/schemas/AgentOwnershipPairingClaimRequest" },
  { name: "AgentOwnershipPairingClaimResult", ref: "#/components/schemas/AgentOwnershipPairingClaimResult" },
  { name: "ProviderAgentOwnershipCallbackRequest", ref: "#/components/schemas/ProviderAgentOwnershipCallbackRequest" },
  { name: "AgentOwnershipRecord", ref: "#/components/schemas/AgentOwnershipRecord" },
  { name: "AgentOwnershipSession", ref: "#/components/schemas/AgentOwnershipSession" },
  { name: "AgentDelegatedCredentialIssueRequest", ref: "#/components/schemas/AgentDelegatedCredentialIssueRequest" },
  { name: "AgentDelegatedCredentialRefreshRequest", ref: "#/components/schemas/AgentDelegatedCredentialRefreshRequest" },
  { name: "AgentDelegatedCredential", ref: "#/components/schemas/AgentDelegatedCredential" },
  { name: "UserAgent", ref: "#/components/schemas/UserAgent" },
  { name: "UserAgentListResponse", ref: "#/components/schemas/UserAgentListResponse" },
  { name: "AgentHandle", ref: "#/components/schemas/AgentHandle" },
  { name: "UpdateAgentHandleRequest", ref: "#/components/schemas/UpdateAgentHandleRequest" },
  { name: "UpdateUserAgentRequest", ref: "#/components/schemas/UpdateUserAgentRequest" },
  { name: "PublicAgentResolution", ref: "#/components/schemas/PublicAgentResolution" },
  { name: "NamespaceVerificationAssertions", ref: "#/components/schemas/NamespaceVerificationAssertions" },
  { name: "NamespaceVerificationCapabilities", ref: "#/components/schemas/NamespaceVerificationCapabilities" },
  { name: "NamespaceVerificationSession", ref: "#/components/schemas/NamespaceVerificationSession" },
  { name: "NamespaceVerification", ref: "#/components/schemas/NamespaceVerification" },
  { name: "SessionExchangeResponse", ref: "#/components/schemas/SessionExchangeResponse" },
  { name: "Community", ref: "#/components/schemas/Community" },
  { name: "CommunityNamespaceAttachRequest", ref: "#/components/schemas/CommunityNamespaceAttachRequest" },
  { name: "CommunityMoneyPolicy", ref: "#/components/schemas/CommunityMoneyPolicy" },
  { name: "CommunityPricingPolicy", ref: "#/components/schemas/CommunityPricingPolicy" },
  { name: "CommunityListing", ref: "#/components/schemas/CommunityListing" },
  { name: "CreateCommunityListingRequest", ref: "#/components/schemas/CreateCommunityListingRequest" },
  { name: "UpdateCommunityListingRequest", ref: "#/components/schemas/UpdateCommunityListingRequest" },
  { name: "CommunityListingListResponse", ref: "#/components/schemas/CommunityListingListResponse" },
  { name: "CommunityPurchase", ref: "#/components/schemas/CommunityPurchase" },
  { name: "CommunityPurchaseListResponse", ref: "#/components/schemas/CommunityPurchaseListResponse" },
  { name: "CommunityPurchaseQuotePreflightRequest", ref: "#/components/schemas/CommunityPurchaseQuotePreflightRequest" },
  { name: "CommunityPurchaseQuotePreflight", ref: "#/components/schemas/CommunityPurchaseQuotePreflight" },
  { name: "CommunityPurchaseQuoteRequest", ref: "#/components/schemas/CommunityPurchaseQuoteRequest" },
  { name: "CommunityPurchaseQuote", ref: "#/components/schemas/CommunityPurchaseQuote" },
  { name: "CommunityPurchaseSettlementRequest", ref: "#/components/schemas/CommunityPurchaseSettlementRequest" },
  { name: "CommunityPurchaseSettlement", ref: "#/components/schemas/CommunityPurchaseSettlement" },
  { name: "CommunityPurchaseSettlementPending", ref: "#/components/schemas/CommunityPurchaseSettlementPending" },
  {
    name: "CommunityPurchaseSettlementFailureRequest",
    ref: "#/components/schemas/CommunityPurchaseSettlementFailureRequest",
  },
  { name: "CommunityPurchaseSettlementFailure", ref: "#/components/schemas/CommunityPurchaseSettlementFailure" },
  { name: "BookingProfile", ref: "#/components/schemas/BookingProfile" },
  { name: "BookingProfileResponse", ref: "#/components/schemas/BookingProfileResponse" },
  { name: "UpdateBookingProfileRequest", ref: "#/components/schemas/UpdateBookingProfileRequest" },
  { name: "AvailabilityRule", ref: "#/components/schemas/AvailabilityRule" },
  { name: "CreateAvailabilityRuleRequest", ref: "#/components/schemas/CreateAvailabilityRuleRequest" },
  { name: "UpdateAvailabilityRuleRequest", ref: "#/components/schemas/UpdateAvailabilityRuleRequest" },
  { name: "AvailabilityException", ref: "#/components/schemas/AvailabilityException" },
  { name: "CreateAvailabilityExceptionRequest", ref: "#/components/schemas/CreateAvailabilityExceptionRequest" },
  { name: "UpdateAvailabilityExceptionRequest", ref: "#/components/schemas/UpdateAvailabilityExceptionRequest" },
  { name: "PriceRule", ref: "#/components/schemas/PriceRule" },
  { name: "CreatePriceRuleRequest", ref: "#/components/schemas/CreatePriceRuleRequest" },
  { name: "UpdatePriceRuleRequest", ref: "#/components/schemas/UpdatePriceRuleRequest" },
  { name: "BookingSlotsResponse", ref: "#/components/schemas/BookingSlotsResponse" },
  { name: "CreateBookingHoldRequest", ref: "#/components/schemas/CreateBookingHoldRequest" },
  { name: "BookingQuote", ref: "#/components/schemas/BookingQuote" },
  { name: "ConfirmBookingHoldRequest", ref: "#/components/schemas/ConfirmBookingHoldRequest" },
  { name: "SubmitBookingPaymentRequest", ref: "#/components/schemas/SubmitBookingPaymentRequest" },
  { name: "BookingPaymentResumeState", ref: "#/components/schemas/BookingPaymentResumeState" },
  { name: "PendingBookingPaymentIntent", ref: "#/components/schemas/PendingBookingPaymentIntent" },
  { name: "UnresolvedBookingPaymentIntent", ref: "#/components/schemas/UnresolvedBookingPaymentIntent" },
  { name: "BookingCancellationPreview", ref: "#/components/schemas/BookingCancellationPreview" },
  { name: "CancelBookingRequest", ref: "#/components/schemas/CancelBookingRequest" },
  { name: "Booking", ref: "#/components/schemas/Booking" },
  { name: "BookingSessionAttachResponse", ref: "#/components/schemas/BookingSessionAttachResponse" },
  { name: "ResolveBookingSettlementReviewRequest", ref: "#/components/schemas/ResolveBookingSettlementReviewRequest" },
  { name: "ResolveBookingSettlementReviewResponse", ref: "#/components/schemas/ResolveBookingSettlementReviewResponse" },
  { name: "CommunityHandle", ref: "#/components/schemas/CommunityHandle" },
  { name: "CommunityHandleProtocolIssuance", ref: "#/components/schemas/CommunityHandleProtocolIssuance" },
  { name: "CommunityHandleClaimRequest", ref: "#/components/schemas/CommunityHandleClaimRequest" },
  { name: "CommunityHandleListResponse", ref: "#/components/schemas/CommunityHandleListResponse" },
  { name: "CommunityHandleMeResponse", ref: "#/components/schemas/CommunityHandleMeResponse" },
  { name: "CommunityHandleStatusResponse", ref: "#/components/schemas/CommunityHandleStatusResponse" },
  { name: "CommunityHandlePolicy", ref: "#/components/schemas/CommunityHandlePolicy" },
  { name: "CommunityHandlePolicySettings", ref: "#/components/schemas/CommunityHandlePolicySettings" },
  { name: "CommunityHandlePaymentInstructions", ref: "#/components/schemas/CommunityHandlePaymentInstructions" },
  { name: "CommunityHandleQuote", ref: "#/components/schemas/CommunityHandleQuote" },
  { name: "CommunityHandleQuoteRequest", ref: "#/components/schemas/CommunityHandleQuoteRequest" },
  { name: "CommunityHandleReserveRequest", ref: "#/components/schemas/CommunityHandleReserveRequest" },
  { name: "CommunityHandleRevokeRequest", ref: "#/components/schemas/CommunityHandleRevokeRequest" },
  { name: "UpdateCommunityHandlePolicyRequest", ref: "#/components/schemas/UpdateCommunityHandlePolicyRequest" },
  { name: "MembershipResult", ref: "#/components/schemas/MembershipResult" },
  { name: "CommunityFollowResponse", ref: "#/components/schemas/CommunityFollowResponse" },
  { name: "Job", ref: "#/components/schemas/Job" },
  { name: "CommunityCreateAcceptedResponse", ref: "#/components/schemas/CommunityCreateAcceptedResponse" },
  { name: "CreateCommunityRequest", ref: "#/components/schemas/CreateCommunityRequest" },
  { name: "GatePolicy", ref: "#/components/schemas/GatePolicy" },
  { name: "GateExpression", ref: "#/components/schemas/GateExpression" },
  { name: "GateAtom", ref: "#/components/schemas/GateAtom" },
  { name: "UpdateCommunityMoneyPolicyRequest", ref: "#/components/schemas/UpdateCommunityMoneyPolicyRequest" },
  { name: "UpdateCommunityPricingPolicyRequest", ref: "#/components/schemas/UpdateCommunityPricingPolicyRequest" },
  { name: "StartVerificationSessionRequest", ref: "#/components/schemas/StartVerificationSessionRequest" },
  { name: "CompleteVerificationSessionRequest", ref: "#/components/schemas/CompleteVerificationSessionRequest" },
  { name: "RefreshPassportWalletScoreRequest", ref: "#/components/schemas/RefreshPassportWalletScoreRequest" },
  { name: "RefreshPassportWalletScoreResponse", ref: "#/components/schemas/RefreshPassportWalletScoreResponse" },
  {
    name: "StartNamespaceVerificationSessionRequest",
    ref: "#/components/schemas/StartNamespaceVerificationSessionRequest",
  },
  {
    name: "CompleteNamespaceVerificationSessionRequest",
    ref: "#/components/schemas/CompleteNamespaceVerificationSessionRequest",
  },
  { name: "CreateSongArtifactUploadRequest", ref: "#/components/schemas/CreateSongArtifactUploadRequest" },
  { name: "CreateSongArtifactBundleRequest", ref: "#/components/schemas/CreateSongArtifactBundleRequest" },
  { name: "CreatePostRequest", ref: "#/components/schemas/CreatePostRequest" },
  { name: "CreateCommentRequest", ref: "#/components/schemas/CreateCommentRequest" },
  { name: "Asset", ref: "#/components/schemas/Asset" },
  { name: "AssetAccessResponse", ref: "#/components/schemas/AssetAccessResponse" },
  { name: "SongArtifactUpload", ref: "#/components/schemas/SongArtifactUpload" },
  { name: "SongArtifactBundle", ref: "#/components/schemas/SongArtifactBundle" },
  { name: "SongArtifactBundleListResponse", ref: "#/components/schemas/SongArtifactBundleListResponse" },
  { name: "SongPreviewGeneratePayload", ref: "#/components/schemas/SongPreviewGeneratePayload" },
  { name: "CrosspostSourceStatus", ref: "#/components/schemas/CrosspostSourceStatus" },
  { name: "CrosspostSource", ref: "#/components/schemas/CrosspostSource" },
  { name: "PostPublishFailureCode", ref: "#/components/schemas/PostPublishFailureCode" },
  { name: "CreatePostListingDraft", ref: "#/components/schemas/CreatePostListingDraft" },
  { name: "Post", ref: "#/components/schemas/Post" },
  { name: "DeletedPostResponse", ref: "#/components/schemas/DeletedPostResponse" },
  { name: "Comment", ref: "#/components/schemas/Comment" },
  { name: "CommentListItem", ref: "#/components/schemas/CommentListItem" },
  { name: "CommentThreadSnapshot", ref: "#/components/schemas/CommentThreadSnapshot" },
  { name: "CommentListResponse", ref: "#/components/schemas/CommentListResponse" },
  { name: "CommentContext", ref: "#/components/schemas/CommentContext" },
  { name: "PostVoteResponse", ref: "#/components/schemas/PostVoteResponse" },
  { name: "CommentVoteResponse", ref: "#/components/schemas/CommentVoteResponse" },
  { name: "ModerationSignalSeverity", ref: "#/components/schemas/ModerationSignalSeverity" },
  { name: "UserReportReasonCode", ref: "#/components/schemas/UserReportReasonCode" },
  { name: "ModerationActionType", ref: "#/components/schemas/ModerationActionType" },
  { name: "CreateUserReportRequest", ref: "#/components/schemas/CreateUserReportRequest" },
  { name: "UserReport", ref: "#/components/schemas/UserReport" },
  { name: "ModerationSignal", ref: "#/components/schemas/ModerationSignal" },
  { name: "ModerationAction", ref: "#/components/schemas/ModerationAction" },
  { name: "ModerationCase", ref: "#/components/schemas/ModerationCase" },
  { name: "ModerationCasePostPreview", ref: "#/components/schemas/ModerationCasePostPreview" },
  { name: "ModerationCaseListItem", ref: "#/components/schemas/ModerationCaseListItem" },
  { name: "ModerationCaseDetail", ref: "#/components/schemas/ModerationCaseDetail" },
  { name: "ModerationCaseListResponse", ref: "#/components/schemas/ModerationCaseListResponse" },
  { name: "CreateModerationActionRequest", ref: "#/components/schemas/CreateModerationActionRequest" },
  { name: "MediaAnalysisResult", ref: "#/components/schemas/MediaAnalysisResult" },
  { name: "RightsReviewCase", ref: "#/components/schemas/RightsReviewCase" },
  { name: "RightsReviewCaseListItem", ref: "#/components/schemas/RightsReviewCaseListItem" },
  { name: "RightsReviewCaseListResponse", ref: "#/components/schemas/RightsReviewCaseListResponse" },
  { name: "RightsReviewCaseDetail", ref: "#/components/schemas/RightsReviewCaseDetail" },
  { name: "CreateRightsReviewActionRequest", ref: "#/components/schemas/CreateRightsReviewActionRequest" },
  { name: "SongPresentation", ref: "#/components/schemas/SongPresentation" },
  { name: "SongStudyCapability", ref: "#/components/schemas/SongStudyCapability" },
  { name: "SongStudyPayload", ref: "#/components/schemas/SongStudyPayload" },
  { name: "SongStudyAccessState", ref: "#/components/schemas/SongStudyAccessState" },
  { name: "SongStudyLockedReason", ref: "#/components/schemas/SongStudyLockedReason" },
  { name: "SongKaraokePayload", ref: "#/components/schemas/SongKaraokePayload" },
  { name: "KaraokeScoringPolicy", ref: "#/components/schemas/KaraokeScoringPolicy" },
  { name: "KaraokeSession", ref: "#/components/schemas/KaraokeSession" },
  { name: "DanceSession", ref: "#/components/schemas/DanceSession" },
  { name: "DanceAttempt", ref: "#/components/schemas/DanceAttempt" },
  { name: "DanceChoreography", ref: "#/components/schemas/DanceChoreography" },
  { name: "KaraokeAttempt", ref: "#/components/schemas/KaraokeAttempt" },
  { name: "KaraokeRankingScope", ref: "#/components/schemas/KaraokeRankingScope" },
  { name: "KaraokeAttemptCompletionReason", ref: "#/components/schemas/KaraokeAttemptCompletionReason" },
  { name: "KaraokeTimingTrend", ref: "#/components/schemas/KaraokeTimingTrend" },
  { name: "KaraokeSongLeaderboard", ref: "#/components/schemas/KaraokeSongLeaderboard" },
  { name: "KaraokeLeaderboardEntry", ref: "#/components/schemas/KaraokeLeaderboardEntry" },
  { name: "KaraokeLeaderboardIdentity", ref: "#/components/schemas/KaraokeLeaderboardIdentity" },
  { name: "SongStudyUnavailableReason", ref: "#/components/schemas/SongStudyUnavailableReason" },
  { name: "SongStudyExercise", ref: "#/components/schemas/SongStudyExercise" },
  { name: "SongStudyRenderSafeExercise", ref: "#/components/schemas/SongStudyRenderSafeExercise" },
  { name: "SongStudyLessonNext", ref: "#/components/schemas/SongStudyLessonNext" },
  { name: "SongStudyLessonState", ref: "#/components/schemas/SongStudyLessonState" },
  { name: "SongStudyRevisionConflict", ref: "#/components/schemas/SongStudyRevisionConflict" },
  { name: "SongStudyAttemptRequest", ref: "#/components/schemas/SongStudyAttemptRequest" },
  { name: "SongStudyAttemptResult", ref: "#/components/schemas/SongStudyAttemptResult" },
  { name: "SongStudyTranscriptionResponse", ref: "#/components/schemas/SongStudyTranscriptionResponse" },
  { name: "TelegramStudyVoiceIntentRequest", ref: "#/components/schemas/TelegramStudyVoiceIntentRequest" },
  { name: "TelegramStudyVoiceIntent", ref: "#/components/schemas/TelegramStudyVoiceIntent" },
  { name: "CreateTelegramAccountLinkIntentRequest", ref: "#/components/schemas/CreateTelegramAccountLinkIntentRequest" },
  { name: "TelegramAccountLinkIntentResponse", ref: "#/components/schemas/TelegramAccountLinkIntentResponse" },
  { name: "ConsumeTelegramAccountLinkIntentRequest", ref: "#/components/schemas/ConsumeTelegramAccountLinkIntentRequest" },
  { name: "TelegramAccountLinkResult", ref: "#/components/schemas/TelegramAccountLinkResult" },
  { name: "SongStreakLeaderboard", ref: "#/components/schemas/SongStreakLeaderboard" },
  { name: "SongStreakLeaderboardEntry", ref: "#/components/schemas/SongStreakLeaderboardEntry" },
  { name: "SongStreakSummary", ref: "#/components/schemas/SongStreakSummary" },
  { name: "SongStreakViewerStanding", ref: "#/components/schemas/SongStreakViewerStanding" },
  { name: "LocalizedPostResponse", ref: "#/components/schemas/LocalizedPostResponse" },
  { name: "LocalizedPostEmbedTranslation", ref: "#/components/schemas/LocalizedPostEmbedTranslation" },
  { name: "MembershipGateSummary", ref: "#/components/schemas/MembershipGateSummary" },
  { name: "MembershipGateExpressionSummary", ref: "#/components/schemas/MembershipGateExpressionSummary" },
  { name: "CommunityPreview", ref: "#/components/schemas/CommunityPreview" },
  { name: "CommunityBranding", ref: "#/components/schemas/CommunityBranding" },
  { name: "CommunityBrandingPatch", ref: "#/components/schemas/CommunityBrandingPatch" },
  { name: "CommunityPresentation", ref: "#/components/schemas/CommunityPresentation" },
  { name: "CommunityPresentationPatch", ref: "#/components/schemas/CommunityPresentationPatch" },
  { name: "JoinEligibility", ref: "#/components/schemas/JoinEligibility" },
  { name: "MembershipRequestStatus", ref: "#/components/schemas/MembershipRequestStatus" },
  { name: "MembershipRequestSummary", ref: "#/components/schemas/MembershipRequestSummary" },
  { name: "MembershipRequestListResponse", ref: "#/components/schemas/MembershipRequestListResponse" },
  { name: "GateFailureDetails", ref: "#/components/schemas/GateFailureDetails" },
  { name: "HomeFeedCommunitySummary", ref: "#/components/schemas/HomeFeedCommunitySummary" },
  { name: "FeedBooking", ref: "#/components/schemas/FeedBooking" },
  { name: "HomeFeedItem", ref: "#/components/schemas/FeedItem" },
  { name: "HomeFeedResponse", ref: "#/components/schemas/FeedResponse" },
  { name: "HomeFeedSort", ref: "#/components/parameters/FeedSort/schema" },
  { name: "LinkedHandle", ref: "#/components/schemas/LinkedHandle" },
  { name: "SelfVerificationDisclosures", ref: "#/components/schemas/SelfVerificationDisclosures" },
  { name: "SelfVerificationLaunch", ref: "#/components/schemas/SelfVerificationLaunch" },
  { name: "UserTaskType", ref: "#/components/schemas/UserTaskType" },
  { name: "UserTaskStatus", ref: "#/components/schemas/UserTaskStatus" },
  { name: "NotificationEventType", ref: "#/components/schemas/NotificationEventType" },
  { name: "UserTask", ref: "#/components/schemas/UserTask" },
  { name: "NotificationEvent", ref: "#/components/schemas/NotificationEvent" },
  { name: "NotificationReceipt", ref: "#/components/schemas/NotificationReceipt" },
  { name: "NotificationSummary", ref: "#/components/schemas/NotificationSummary" },
  { name: "NotificationFeedItem", ref: "#/components/schemas/NotificationFeedItem" },
  { name: "NotificationFeedResponse", ref: "#/components/schemas/NotificationFeedResponse" },
  { name: "NotificationTasksResponse", ref: "#/components/schemas/NotificationTasksResponse" },
  { name: "MarkNotificationsReadRequest", ref: "#/components/schemas/MarkNotificationsReadRequest" },
  { name: "DismissTaskRequest", ref: "#/components/schemas/DismissTaskRequest" },
  { name: "RewardVerificationState", ref: "#/components/schemas/RewardVerificationState" },
  { name: "RewardEventKind", ref: "#/components/schemas/RewardEventKind" },
  { name: "RewardEventSummary", ref: "#/components/schemas/RewardEventSummary" },
  { name: "RewardQualificationStatus", ref: "#/components/schemas/RewardQualificationStatus" },
  { name: "RewardQualificationOutcomeReason", ref: "#/components/schemas/RewardQualificationOutcomeReason" },
  { name: "RewardQualificationSummary", ref: "#/components/schemas/RewardQualificationSummary" },
  { name: "RewardsCashoutSummary", ref: "#/components/schemas/RewardsCashoutSummary" },
  { name: "RewardsSummaryResponse", ref: "#/components/schemas/RewardsSummaryResponse" },
  { name: "RewardPayoutStatus", ref: "#/components/schemas/RewardPayoutStatus" },
  { name: "RewardPayoutSummary", ref: "#/components/schemas/RewardPayoutSummary" },
  { name: "RewardCashoutWalletProof", ref: "#/components/schemas/RewardCashoutWalletProof" },
  { name: "RewardCashoutRequest", ref: "#/components/schemas/RewardCashoutRequest" },
  { name: "RewardCashoutResponse", ref: "#/components/schemas/RewardCashoutResponse" },
  { name: "RewardCampaignStatus", ref: "#/components/schemas/RewardCampaignStatus" },
  { name: "RewardCampaignIncidentRecoveryRequest", ref: "#/components/schemas/RewardCampaignIncidentRecoveryRequest" },
  { name: "RewardCampaignIncidentRecoveryResponse", ref: "#/components/schemas/RewardCampaignIncidentRecoveryResponse" },
  { name: "RewardCampaignEligibleActivity", ref: "#/components/schemas/RewardCampaignEligibleActivity" },
  { name: "RewardIdentityBindingCapability", ref: "#/components/schemas/RewardIdentityBindingCapability" },
  { name: "RewardIdentityBindingDocument", ref: "#/components/schemas/RewardIdentityBindingDocument" },
  { name: "RewardIdentityBinding", ref: "#/components/schemas/RewardIdentityBinding" },
  { name: "RewardIdentityBindingResponse", ref: "#/components/schemas/RewardIdentityBindingResponse" },
  { name: "RewardIdentityBindingSelectRequest", ref: "#/components/schemas/RewardIdentityBindingSelectRequest" },
  { name: "RewardCampaignCapabilities", ref: "#/components/schemas/RewardCampaignCapabilities" },
  { name: "RewardCampaignPayoutTier", ref: "#/components/schemas/RewardCampaignPayoutTier" },
  { name: "PublicRewardOffer", ref: "#/components/schemas/PublicRewardOffer" },
  { name: "RewardSongOwnerPolicy", ref: "#/components/schemas/RewardSongOwnerPolicy" },
  { name: "RewardSongOwnerPolicyUpdateRequest", ref: "#/components/schemas/RewardSongOwnerPolicyUpdateRequest" },
  { name: "RewardCampaign", ref: "#/components/schemas/RewardCampaign" },
  { name: "RewardCampaignCreateRequest", ref: "#/components/schemas/RewardCampaignCreateRequest" },
  { name: "RewardCampaignFundingStatus", ref: "#/components/schemas/RewardCampaignFundingStatus" },
  { name: "RewardCampaignFundingQuote", ref: "#/components/schemas/RewardCampaignFundingQuote" },
  { name: "RewardCampaignFundingQuoteRequest", ref: "#/components/schemas/RewardCampaignFundingQuoteRequest" },
  { name: "RewardCampaignFundingConfirmRequest", ref: "#/components/schemas/RewardCampaignFundingConfirmRequest" },
  { name: "RewardPoolRefundPolicyReadiness", ref: "#/components/schemas/RewardPoolRefundPolicyReadiness" },
  { name: "RewardBackendFlipReadiness", ref: "#/components/schemas/RewardBackendFlipReadiness" },
  { name: "RewardSolvencyReadiness", ref: "#/components/schemas/RewardSolvencyReadiness" },
  { name: "ClaimableRoyaltyItem", ref: "#/components/schemas/ClaimableRoyaltyItem" },
  { name: "ClaimableRoyaltiesResponse", ref: "#/components/schemas/ClaimableRoyaltiesResponse" },
  { name: "RoyaltyActivityItem", ref: "#/components/schemas/RoyaltyActivityItem" },
  { name: "RoyaltyActivityResponse", ref: "#/components/schemas/RoyaltyActivityResponse" },
  { name: "RoyaltyClaimRecordRequest", ref: "#/components/schemas/RoyaltyClaimRecordRequest" },
  { name: "RoyaltyClaimRecord", ref: "#/components/schemas/RoyaltyClaimRecord" },
  { name: "RoyaltyClaimHistoryResponse", ref: "#/components/schemas/RoyaltyClaimHistoryResponse" },
] as const;

const ROUTE_EXPORTS = [
  { name: "authSessionExchange", path: "/auth/session/exchange" },
  { name: "usersMe", path: "/users/me" },
  { name: "usersMeTelegramAccountLinkIntents", path: "/users/me/telegram-account-link-intents" },
  { name: "usersMeTelegramAccountLinkIntentsConsume", path: "/users/me/telegram-account-link-intents/consume" },
  { name: "profilesMe", path: "/profiles/me" },
  { name: "profilesMeCourtyardInventory", path: "/profiles/me/courtyard-inventory" },
  { name: "gateCapabilitiesAssets", path: "/gate-capabilities/assets" },
  { name: "gateCapabilitiesNftSources", path: "/gate-capabilities/nft/sources" },
  {
    name: "gateCapabilitiesNftSourceFacetValues",
    path: "/gate-capabilities/nft/sources/{source_id}/facets/{facet_key}/values",
  },
  { name: "walletIdentity", path: "/wallet-identities/{chain_ref}/{wallet_address}" },
  { name: "publicNameQuotes", path: "/public-names/quotes" },
  { name: "publicNameClaims", path: "/public-names/claims" },
  { name: "publicNameStatus", path: "/public-names/{label}/status" },
  { name: "onboardingStatus", path: "/onboarding/status" },
  { name: "onboardingDismiss", path: "/onboarding/dismiss" },
  { name: "onboardingRedditVerification", path: "/onboarding/reddit-verification" },
  { name: "onboardingRedditImports", path: "/onboarding/reddit-imports" },
  { name: "onboardingRedditImportsLatest", path: "/onboarding/reddit-imports/latest" },
  { name: "verificationSessions", path: "/verification-sessions" },
  { name: "verificationSession", path: "/verification-sessions/{verification_session_id}" },
  { name: "verificationSessionComplete", path: "/verification-sessions/{verification_session_id}/complete" },
  { name: "passportWalletScore", path: "/verification/passport-wallet-score" },
  { name: "altchaChallenge", path: "/verification/altcha/challenge" },
  { name: "agentOwnershipSessions", path: "/agent-ownership-sessions" },
  { name: "agentOwnershipPairing", path: "/agent-ownership-pairing" },
  { name: "agentOwnershipPairingClaim", path: "/agent-ownership-pairing/claim" },
  { name: "agentOwnershipSession", path: "/agent-ownership-sessions/{agent_ownership_session_id}" },
  {
    name: "agentOwnershipSessionComplete",
    path: "/agent-ownership-sessions/{agent_ownership_session_id}/complete",
  },
  { name: "agents", path: "/agents" },
  { name: "agent", path: "/agents/{agent_id}" },
  { name: "agentHandle", path: "/agents/{agent_id}/handle" },
  { name: "agentCredential", path: "/agents/{agent_id}/credential" },
  { name: "agentCredentialRefresh", path: "/agents/{agent_id}/refresh-credential" },
  { name: "publicAgent", path: "/public-agents/{handle_label}" },
  { name: "namespaceVerificationSessions", path: "/namespace-verification-sessions" },
  { name: "namespaceVerificationSession", path: "/namespace-verification-sessions/{namespace_verification_session_id}" },
  {
    name: "namespaceVerificationSessionComplete",
    path: "/namespace-verification-sessions/{namespace_verification_session_id}/complete",
  },
  { name: "namespaceVerification", path: "/namespace-verifications/{namespace_verification_id}" },
  { name: "communities", path: "/communities" },
  { name: "communitiesAdminHealth", path: "/communities/admin/health" },
  { name: "community", path: "/communities/{community_id}" },
  { name: "communityNamespace", path: "/communities/{community_id}/namespace" },
  { name: "communityMoneyPolicy", path: "/communities/{community_id}/money-policy" },
  { name: "communityPricingPolicy", path: "/communities/{community_id}/pricing-policy" },
  { name: "communityListings", path: "/communities/{community_id}/listings" },
  { name: "communityListing", path: "/communities/{community_id}/listings/{listing_id}" },
  { name: "communityPurchases", path: "/communities/{community_id}/purchases" },
  { name: "communityPurchase", path: "/communities/{community_id}/purchases/{purchase_id}" },
  { name: "communityPurchaseQuotePreflight", path: "/communities/{community_id}/purchase-quote-preflight" },
  { name: "communityPurchaseQuotes", path: "/communities/{community_id}/purchase-quotes" },
  { name: "communityPurchaseSettlements", path: "/communities/{community_id}/purchase-settlements" },
  { name: "communityPurchaseSettlementFailures", path: "/communities/{community_id}/fail-purchase-settlement" },
  { name: "bookings", path: "/bookings" },
  { name: "bookingHostSlots", path: "/bookings/hosts/{host_user_id}/slots" },
  { name: "bookingHostHolds", path: "/bookings/hosts/{host_user_id}/holds" },
  { name: "bookingHoldQuote", path: "/bookings/holds/{hold_id}/quote" },
  { name: "bookingHoldConfirm", path: "/bookings/holds/{hold_id}/confirm" },
  { name: "bookingHoldPaymentSubmitted", path: "/bookings/holds/{hold_id}/payment-submitted" },
  { name: "bookingPaymentIntentsPending", path: "/bookings/payment-intents/pending" },
  { name: "bookingPaymentIntentsUnresolved", path: "/bookings/payment-intents/unresolved" },
  { name: "booking", path: "/bookings/{booking_id}" },
  { name: "bookingCancellationPreview", path: "/bookings/{booking_id}/cancellation-preview" },
  { name: "bookingCancel", path: "/bookings/{booking_id}/cancel" },
  { name: "bookingStart", path: "/bookings/{booking_id}/start" },
  { name: "bookingComplete", path: "/bookings/{booking_id}/complete" },
  { name: "bookingNoShow", path: "/bookings/{booking_id}/no-show" },
  { name: "bookingSessionAttach", path: "/bookings/{booking_id}/session/attach" },
  { name: "bookingSessionHeartbeat", path: "/bookings/{booking_id}/session/heartbeat" },
  { name: "bookingSettlementReviewPending", path: "/bookings/settlement-review/pending" },
  { name: "bookingSettlementReview", path: "/bookings/{booking_id}/settlement-review" },
  { name: "bookingSettlementReviewResolve", path: "/bookings/{booking_id}/settlement-review/resolve" },
  { name: "hostBookingProfile", path: "/host-bookings/me/profile" },
  { name: "hostBookingProfilePublish", path: "/host-bookings/me/profile/publish" },
  { name: "hostBookingProfileUnpublish", path: "/host-bookings/me/profile/unpublish" },
  { name: "hostBookingAvailabilityRules", path: "/host-bookings/me/availability-rules" },
  { name: "hostBookingAvailabilityRule", path: "/host-bookings/me/availability-rules/{rule_id}" },
  { name: "hostBookingAvailabilityExceptions", path: "/host-bookings/me/availability-exceptions" },
  {
    name: "hostBookingAvailabilityException",
    path: "/host-bookings/me/availability-exceptions/{exception_id}",
  },
  { name: "hostBookingPriceRules", path: "/host-bookings/me/price-rules" },
  { name: "hostBookingPriceRule", path: "/host-bookings/me/price-rules/{price_rule_id}" },
  { name: "communityFollow", path: "/communities/{community_id}/follow" },
  { name: "communityUnfollow", path: "/communities/{community_id}/unfollow" },
  { name: "communityPosts", path: "/communities/{community_id}/posts" },
  { name: "communityPendingPosts", path: "/communities/{community_id}/posts/pending" },
  { name: "communityPostComments", path: "/communities/{community_id}/posts/{post_id}/comments" },
  { name: "communityPostReports", path: "/communities/{community_id}/posts/{post_id}/reports" },
  { name: "communityPostPublishRetry", path: "/communities/{community_id}/posts/{post_id}/publish-retry" },
  { name: "communityCommentReports", path: "/communities/{community_id}/comments/{comment_id}/reports" },
  { name: "communityModerationCases", path: "/communities/{community_id}/moderation/cases" },
  { name: "communityModerationCase", path: "/communities/{community_id}/moderation/cases/{moderation_case_id}" },
  { name: "communityModerationCaseActions", path: "/communities/{community_id}/moderation/cases/{moderation_case_id}/actions" },
  { name: "communityRightsReviewCases", path: "/communities/{community_id}/rights-review/cases" },
  { name: "communityRightsReviewCase", path: "/communities/{community_id}/rights-review/cases/{rights_review_case_id}" },
  {
    name: "communityRightsReviewCaseActions",
    path: "/communities/{community_id}/rights-review/cases/{rights_review_case_id}/actions",
  },
  { name: "communityPreview", path: "/communities/{community_id}/preview" },
  { name: "communityJoinEligibility", path: "/communities/{community_id}/join-eligibility" },
  {
    name: "communityLiveRoomRecordingDraft",
    path: "/communities/{community_id}/live-rooms/{live_room_id}/recording-draft",
  },
  {
    name: "communityLiveRoomReplayDraft",
    path: "/communities/{community_id}/live-rooms/{live_room_id}/replay-draft",
  },
  {
    name: "communityLiveRoomReplayDraftPublish",
    path: "/communities/{community_id}/live-rooms/{live_room_id}/replay-draft/publish",
  },
  {
    name: "communityLiveRoomReplayAccess",
    path: "/communities/{community_id}/live-rooms/{live_room_id}/replay/access",
  },
  {
    name: "communityLiveRoomReplayContent",
    path: "/communities/{community_id}/live-rooms/{live_room_id}/replay/content",
  },
  {
    name: "publicCommunityLiveRoomReplayAccess",
    path: "/public-communities/{community_id}/live-rooms/{live_room_id}/replay/access",
  },
  {
    name: "publicCommunityLiveRoomReplayContent",
    path: "/public-communities/{community_id}/live-rooms/{live_room_id}/replay/content",
  },
  { name: "communityJoin", path: "/communities/{community_id}/join" },
  { name: "communityMembershipRequests", path: "/communities/{community_id}/membership-requests" },
  {
    name: "communityMembershipRequestApprove",
    path: "/communities/{community_id}/membership-requests/{membership_request_id}/approve",
  },
  {
    name: "communityMembershipRequestReject",
    path: "/communities/{community_id}/membership-requests/{membership_request_id}/reject",
  },
  { name: "communitySongArtifactUploads", path: "/communities/{community_id}/song-artifact-uploads" },
  {
    name: "communitySongArtifactUploadContent",
    path: "/communities/{community_id}/song-artifact-uploads/{song_artifact_upload_id}/content",
  },
  { name: "communitySongArtifacts", path: "/communities/{community_id}/song-artifacts" },
  { name: "communitySongArtifact", path: "/communities/{community_id}/song-artifacts/{song_artifact_bundle_id}" },
  { name: "communityPostStudy", path: "/communities/{community_id}/posts/{post_id}/study" },
  { name: "communityPostStudyAttempts", path: "/communities/{community_id}/posts/{post_id}/study/attempts" },
  { name: "communityPostStudyTelegramVoiceIntents", path: "/communities/{community_id}/posts/{post_id}/study/telegram_voice_intents" },
  { name: "communityPostStudyTranscriptions", path: "/communities/{community_id}/posts/{post_id}/study/transcriptions" },
  { name: "communityPostStreaksLeaderboard", path: "/communities/{community_id}/posts/{post_id}/streaks/leaderboard" },
  { name: "communityPostKaraokeLeaderboard", path: "/communities/{community_id}/posts/{post_id}/karaoke/leaderboard" },
  { name: "communityPostKaraokeSession", path: "/communities/{community_id}/posts/{post_id}/karaoke/sessions" },
  { name: "karaokeSessionWebsocket", path: "/karaoke/sessions/{session_id}/websocket" },
  { name: "danceSession", path: "/dance-sessions/{dance_session_id}" },
  { name: "danceSessionCancel", path: "/dance-sessions/{dance_session_id}/cancel" },
  { name: "danceAttempt", path: "/dance-attempts/{dance_attempt_id}" },
  { name: "danceChoreography", path: "/dance-choreographies/{dance_choreography_id}" },
  { name: "postDanceChoreography", path: "/posts/{post_id}/dance-choreography" },
  { name: "job", path: "/jobs/{job_id}" },
  { name: "post", path: "/posts/{post_id}" },
  { name: "postVote", path: "/posts/{post_id}/vote" },
  { name: "communityPostRemove", path: "/communities/{community_id}/posts/{post_id}/remove" },
  { name: "communityPostCommentsLock", path: "/communities/{community_id}/posts/{post_id}/comments-lock" },
  { name: "commentRemove", path: "/comments/{comment_id}/remove" },
  { name: "commentDelete", path: "/comments/{comment_id}/delete" },
  { name: "commentRepliesLock", path: "/comments/{comment_id}/replies-lock" },
  { name: "commentReplies", path: "/comments/{comment_id}/replies" },
  { name: "commentContext", path: "/comments/{comment_id}/context" },
  { name: "commentVote", path: "/comments/{comment_id}/vote" },
  { name: "notificationsSummary", path: "/notifications/summary" },
  { name: "notificationsTasks", path: "/notifications/tasks" },
  { name: "notificationsFeed", path: "/notifications/feed" },
  { name: "notificationsMarkRead", path: "/notifications/mark-read" },
  { name: "notificationsDismissTask", path: "/notifications/dismiss-task" },
  { name: "meRewards", path: "/me/rewards" },
  { name: "meRewardsIdentityBinding", path: "/me/rewards/identity-binding" },
  { name: "meRewardsCashouts", path: "/me/rewards/cashouts" },
  { name: "rewardCampaigns", path: "/reward_campaigns" },
  { name: "rewardSongPolicies", path: "/reward_song_policies/{community_id}/{post_id}" },
  { name: "rewardCampaign", path: "/reward_campaigns/{campaign_id}" },
  { name: "rewardCampaignCancel", path: "/reward_campaigns/{campaign_id}/cancel" },
  { name: "rewardCampaignCapabilities", path: "/reward_campaign_capabilities" },
  { name: "publicRewardCampaign", path: "/public/reward_campaigns/{campaign_id}" },
  { name: "publicRewardCampaigns", path: "/public/reward_campaigns" },
  { name: "operatorRewardCampaignIncidentRecovery", path: "/operator/reward_campaigns/{campaign_id}/incidents/{incident_id}/recover" },
  { name: "operatorRewardPoolRefundPolicyReadiness", path: "/operator/reward_pools/refund_policy_readiness" },
  { name: "operatorRewardSettlementBackendFlipReadiness", path: "/operator/reward_settlements/backend_flip_readiness" },
  { name: "operatorRewardSettlementSolvencyReadiness", path: "/operator/reward_settlements/solvency_readiness" },
  { name: "rewardCampaignFundingQuotes", path: "/reward_campaigns/{campaign_id}/funding_quotes" },
  { name: "rewardCampaignFundingQuoteConfirm", path: "/reward_campaigns/{campaign_id}/funding_quotes/{funding_quote_id}/confirm" },
] as const;

const GENERATED_FILE_BANNER = `// GENERATED FILE. Edit specs/api/src/** and run \`rtk bun specs/api/scripts/generate-api-contracts.ts\`.\n`;

function toCamelCase(value: string): string {
  return value.replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase());
}

function renderRoute(entry: { name: string; path: string }): string {
  const params = Array.from(entry.path.matchAll(/\{([^}]+)\}/g)).map((match) => match[1]);
  if (params.length === 0) {
    return `  ${entry.name}: ${JSON.stringify(entry.path)},`;
  }

  const argumentsList = params.map((param) => `${toCamelCase(param)}: string`).join(", ");
  let template = entry.path;
  for (const param of params) {
    template = template.replace(`{${param}}`, `\${${toCamelCase(param)}}`);
  }

  return `  ${entry.name}: (${argumentsList}) => \`${template}\`,`;
}

function renderRoutes(bundle: BundleSpec): string {
  const pathKeys = new Set(Object.keys(bundle.paths ?? {}));
  for (const entry of ROUTE_EXPORTS) {
    if (!pathKeys.has(entry.path)) {
      throw new Error(`Missing implemented route ${entry.path}`);
    }
  }

  return `export const apiRoutes = {\n${ROUTE_EXPORTS.map(renderRoute).join("\n")}\n} as const\n`;
}

async function main() {
  const bundle = parse(await Bun.file(IMPLEMENTED_BUNDLE_FILE).text()) as BundleSpec;
  const sourceSchemas = await loadSourceSchemas(SOURCE_SCHEMA_DIR);
  const generator = new TypeGenerator(bundle, sourceSchemas, TYPE_EXPORTS);
  const output = `${GENERATED_FILE_BANNER}\n${generator.generate(TYPE_EXPORTS)}\n${renderRoutes(bundle)}`;

  await Bun.write(OUTPUT_FILE, output);
  console.log(
    JSON.stringify(
      {
        output: OUTPUT_FILE,
        exported_types: TYPE_EXPORTS.map((entry) => entry.name),
        exported_type_count: TYPE_EXPORTS.length,
        exported_routes: ROUTE_EXPORTS.map((entry) => entry.name),
        exported_route_count: ROUTE_EXPORTS.length,
      },
      null,
      2,
    ),
  );
}

await main();
