import type { Community } from "../types/api";
import type { CommunityRow } from "../types/db";

export function serializeCommunity(row: CommunityRow): Community {
  return {
    community_id: row.community_id,
    display_name: row.display_name,
    description: null,
    namespace_verification_id: row.namespace_verification_id,
    status: row.status === "suspended" ? "frozen" : row.status,
    provisioning_state: row.provisioning_state,
    registry_publication_state: row.registry_publication_state,
    registry_attempt_id: row.registry_attempt_id,
    registry_published_at: row.registry_published_at,
    registry_publication_job_id: row.registry_publication_job_id,
    registry_error_code: row.registry_error_code,
    artist_identity_id: null,
    community_agent_user_id: null,
    membership_mode: row.membership_mode,
    allow_anonymous_identity: false,
    anonymous_identity_scope: null,
    allowed_disclosed_qualifiers: null,
    allow_qualifiers_on_anonymous_posts: null,
    root_post_min_trust_tier: null,
    reply_min_trust_tier: null,
    anonymous_posting_min_trust_tier: null,
    root_post_quota_by_trust_tier: null,
    reply_quota_by_trust_tier: null,
    probation_window_days: null,
    link_post_policy: null,
    default_age_gate_policy: "none",
    agent_posting_policy: "disallow",
    agent_posting_scope: "replies_only",
    agent_daily_post_cap: null,
    agent_daily_reply_cap: null,
    agent_min_owner_trust_tier: null,
    agent_owner_active_limit: null,
    civic_scale_tier: "club",
    governance_mode: "centralized",
    donation_policy_mode: "none",
    donation_partner_status: "unconfigured",
    donation_partner_id: null,
    donation_partner: null,
    content_authenticity_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      authenticity_stance: "human_first",
      text_policy: {
        allow_ai_assisted_editing: false,
        allow_ai_generated: false,
      },
      image_policy: {
        allow_ai_upscale: false,
        allow_ai_restoration: false,
        allow_generative_editing: false,
        allow_ai_generated: false,
      },
      video_policy: {
        allow_ai_upscale: false,
        allow_ai_restoration: false,
        allow_ai_frame_interpolation: false,
        allow_generative_editing: false,
        allow_ai_generated: false,
      },
      song_policy: {
        allow_ai_assisted_mastering: false,
        allow_ai_stem_separation: false,
        allow_ai_generated_instrumentals: false,
        allow_ai_generated_lyrics: false,
        allow_ai_generated_vocals: false,
      },
      updated_at: row.updated_at,
    },
    content_authenticity_detection_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      selection_mode: "platform_default",
      resolved_profile: {
        authenticity_detection_profile_id: "adp_platform_default_v0",
        profile_key: "platform-default",
        provider_key: "platform-default",
        supported_capabilities: [],
        status: "active",
      },
      updated_at: row.updated_at,
    },
    market_context_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      mode: "on",
      enabled_post_types: ["link"],
      max_markets_per_post: 2,
      provider_set: "platform_default",
      resolved_profile: {
        market_context_profile_id: "mcp_platform_default_v1",
        profile_key: "platform-default-v1",
        provider_keys: ["kalshi", "polymarket"],
        status: "active",
      },
      updated_at: row.updated_at,
    },
    source_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      identified_person_media_scope: "subject_only",
      require_source_url_for_reposts: true,
      allow_human_made_fan_art_of_real_people: false,
      require_fan_art_disclosure: false,
      updated_at: row.updated_at,
    },
    capture_edit_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      basic_adjustments: "allow",
      retouching: "disallow",
      compositing: "disallow",
      documentary_editing: "disallow",
      require_edit_disclosure: false,
      updated_at: row.updated_at,
    },
    adult_content_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      suggestive: "review",
      artistic_nudity: "disallow",
      explicit_nudity: "disallow",
      explicit_sexual_content: "disallow",
      fetish_content: "disallow",
      updated_at: row.updated_at,
    },
    graphic_content_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      injury_medical: "review",
      gore: "disallow",
      extreme_gore: "disallow",
      body_horror_disturbing: "disallow",
      animal_harm: "disallow",
      updated_at: row.updated_at,
    },
    motion_media_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      allow_animated_images: true,
      allow_silent_looping_video: true,
      allow_audio_video: true,
      max_video_duration_seconds: null,
      require_video_transcription: false,
      updated_at: row.updated_at,
    },
    language_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      profanity: "allow",
      slurs: "disallow",
      updated_at: row.updated_at,
    },
    provenance_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      allowed_creator_relations: ["captured", "created", "subject", "authorized_repost", "fan_work", "found"],
      require_creator_relation: false,
      false_claim_consequence: "post_removed",
      allow_oc_claim: false,
      require_proof_for_original: false,
      updated_at: row.updated_at,
    },
    promotion_policy: {
      community_id: row.community_id,
      policy_origin: "default",
      self_promotion_mode: "limited_with_disclosure",
      require_affiliation_disclosure: true,
      max_promotional_posts_per_week: 1,
      promotional_participation_ratio: null,
      require_minimum_membership_days: 7,
      updated_at: row.updated_at,
    },
    label_policy: null,
    community_profile: null,
    reference_links: null,
    community_stage: "initial",
    member_count: null,
    qualified_member_count: null,
    stage_entered_at: null,
    governance_backend: null,
    gate_rules: null,
    created_by_user_id: row.creator_user_id,
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}
