[Service]
ExecStart=
ExecStart=/usr/local/bin/pirate-caddy run --environ --config /etc/caddy/caddy.json
ExecReload=
ExecReload=/usr/local/bin/pirate-caddy reload --config /etc/caddy/caddy.json --force
